# Generated by Django 4.1.7 on 2023-03-23 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("food_delivery_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="payInfo",
            fields=[
                ("infoId", models.AutoField(primary_key=True, serialize=False)),
                ("payMode", models.CharField(max_length=100)),
                ("payDescr", models.CharField(max_length=100)),
                (
                    "custId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_delivery_app.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                ("itemId", models.AutoField(primary_key=True, serialize=False)),
                ("price", models.IntegerField()),
                ("description", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                (
                    "restaurant_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_delivery_app.restaurant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("payId", models.AutoField(primary_key=True, serialize=False)),
                ("payDate", models.DateTimeField()),
                (
                    "infoId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_delivery_app.payinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                ("delivery_id", models.AutoField(primary_key=True, serialize=False)),
                ("timeDispatch", models.DateTimeField()),
                ("timeArrival", models.DateTimeField()),
                (
                    "orderId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_delivery_app.orders",
                    ),
                ),
                (
                    "personnelId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_delivery_app.deliverypersonnel",
                    ),
                ),
                (
                    "statusId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_delivery_app.status",
                    ),
                ),
            ],
        ),
    ]
